version: '3'
services:
  redis-test:
    container_name: redis-test
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=cibilex
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - '6379:6379'
    volumes:
      - redis-test:/bitnami/redis/data
volumes:
  redis-test: